modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal_dynamics"
version = "${file.jarVersion}"
displayName = "Thermal Dynamics"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Dynamics!
'''
[[dependencies.thermal_dynamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "forge"
mandatory = true
versionRange = "[31.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.7,0.8]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "thermal"
mandatory = true
versionRange = "[0.3,0.4]"
ordering = "AFTER"
side = "BOTH"