modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_innovation"
version = "${file.jarVersion}"
displayName = "Thermal Innovation"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Technology marches on. Adds Thermal-style tools and equipment!

Contains a number of useful tools, gadgets, and armor.
'''
[[dependencies.thermal_innovation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "forge"
mandatory = true
versionRange = "[34.1.40,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.0.3,1.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_innovation]]
modId = "thermal"
mandatory = true
versionRange = "[1.0.3,1.1]"
ordering = "AFTER"
side = "BOTH"