modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal_locomotion"
version = "${file.jarVersion}"
displayName = "Thermal Locomotion"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal hits the tracks!

Contains the "railyard" of the Thermal Series - Rails and Minecarts to expand rail-centric gameplay.
'''
[[dependencies.thermal_locomotion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_locomotion]]
modId = "forge"
mandatory = true
versionRange = "[31.2.30,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_locomotion]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.7,0.8]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_locomotion]]
modId = "thermal"
mandatory = true
versionRange = "[0.3,0.4]"
ordering = "AFTER"
side = "BOTH"