modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license="https://github.com/Vazkii/Quark/blob/master/LICENSE.md"

[[mods]]
modId = "cofh_core"
version = "${file.jarVersion}"
displayName = "CoFH Core"
updateJSONURL = "https://raw.github.com/cofh/version/master/cofh_core/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming, Zeldo Kavira, covers1624, skyboy, Cynycal, Drullkus"
description = '''
Core Library required for the functionality of all CoFH mods.

Also contains a number of optional gameplay tweaks for convenience.
'''
[[dependencies.cofh_core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cofh_core]]
modId = "forge"
mandatory = true
versionRange = "[34.1.0,)"
ordering = "AFTER"
side = "BOTH"