modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal_cultivation"
version = "${file.jarVersion}"
displayName = "Thermal Cultivation"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal gets agrarian!

Contains the "farm" of the Thermal Series - various crops, foods, and associated gadgetry.
'''
[[dependencies.thermal_cultivation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "forge"
mandatory = true
versionRange = "[31.2.30,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.7,0.8]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "thermal"
mandatory = true
versionRange = "[0.3,0.4]"
ordering = "AFTER"
side = "BOTH"